services:
  - type: web
    name: house-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUNBUFFERED
        value: "true" 