services:
  - type: web
    name: house-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2 --worker-class gthread
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PYTHONUNBUFFERED
        value: "true"
    healthCheckPath: /health
    autoDeploy: true 