services:
  - type: web
    name: house-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn application:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7 